In [1]:
from DataFunctions import *
import datetime
import pandas as pd
import wbdata
import numpy as np
pd.options.mode.chained_assignment = None  # default='warn'

In [ ]:
wbdata.search_indicators("")

In [2]:
indicator_dataframe, indicators, tabnames=GetIndicatorsWB(file='Selected_Indicators.xlsx', sheet='Blad1')

In [3]:
indicator_dataframe

,Indicator,Description,Tabname
0,SP.POP.0014.TO,"Population, ages 0-14, total",NaN
1,SP.POP.1519.FE.5Y,"Population ages 15-19, female (% of female pop...",NaN
2,SP.POP.1519.MA.5Y,"Population ages 15-19, male (% of male populat...",NaN
3,SP.POP.2024.FE.5Y,"Population ages 20-24, female (% of female pop...",NaN
4,SP.POP.2024.MA.5Y,"Population ages 20-24, male (% of male populat...",NaN
5,SP.POP.2529.FE.5Y,"Population ages 25-29, female (% of female pop...",NaN
6,SP.POP.2529.MA.5Y,"Population ages 25-29, male (% of male populat...",NaN
7,SP.POP.3034.FE.5Y,"Population ages 30-34, female (% of female pop...",NaN
8,SP.POP.3034.MA.5Y,"Population ages 30-34, male (% of male populat...",NaN
9,SP.POP.3539.FE.5Y,"Population ages 35-39, female (% of female pop...",NaN
10,SP.POP.3539.MA.5Y,"Population ages 35-39, male (% of male populat...",NaN
11,SP.POP.4044.FE.5Y,"Population ages 40-44, female (% of female pop...",NaN
12,SP.POP.4044.MA.5Y,"Population ages 40-44, male (% of male populat...",NaN
13,SP.POP.4549.FE.5Y,"Population ages 45-49, female (% of female pop...",NaN
14,SP.POP.4549.MA.5Y,"Population ages 45-49, male (% of male populat...",NaN
15,SP.POP.5054.FE.5Y,"Population ages 50-54, female (% of female pop...",NaN
16,SP.POP.5054.MA.5Y,"Population ages 50-54, male (% of male populat...",NaN
17,SP.POP.5559.FE.5Y,"Population ages 55-59, female (% of female pop...",NaN
18,SP.POP.5559.MA.5Y,"Population ages 55-59, male (% of male populat...",NaN
19,SP.POP.6064.FE.5Y,"Population ages 50-64, female (% of female pop...",NaN
20,SP.POP.6064.MA.5Y,"Population ages 50-64, male (% of male populat...",NaN
21,SP.POP.65UP.TO.ZS,Population ages 65 and above (% of total),NaN
22,SP.POP.TOTL,"Population, total",ini pop
23,SP.POP.TOTL.FE.IN,"Population, female",TotalPopulationFemale
24,SP.POP.TOTL.MA.IN,"Population, male",TotalPopulationMale
25,NY.GDP.MKTP.CD,GDP (current US$),ini GDP
26,NY.GDP.MKTP.KD.ZG,GDP growth (annual %),avg net GDP growth rate
27,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",ini life exp
28,SP.URB.TOTL.IN.ZS,Urban population (% of total),ini pc urban
29,SP.URB.GROW,Urban population growth (annual %),urbanisation rate
30,SH.DYN.MORT,"Mortality rate, under-5 (per 1,000 live births)",mortality rate under five
31,SP.DYN.CBRT.IN,"Birth rate, crude (per 1,000 people)",crude birth rate
32,SP.DYN.TFRT.IN,"Fertility rate, total (births per woman)",ini avg nmbr of children per Yaf
33,NV.AGR.TOTL.ZS,"Agriculture, value added (% of GDP)",agriculture value added GDP
34,NV.IND.MANF.ZS,"Manufacturing, value added (% of GDP)",manufacturing value added GDP
35,NV.IND.TOTL.ZS,"Industry, value added (% of GDP)",industry value added GDP
36,NV.SRV.TETC.ZS,"Services, etc., value added (% of GDP)",services etc value added GDP

In [4]:
indicators

{'NV.AGR.TOTL.ZS': 'Agriculture, value added (% of GDP)',
 'NV.IND.MANF.ZS': 'Manufacturing, value added (% of GDP)',
 'NV.IND.TOTL.ZS': 'Industry, value added (% of GDP)',
 'NV.SRV.TETC.ZS': 'Services, etc., value added (% of GDP)',
 'NY.GDP.MKTP.CD': 'GDP (current US$)',
 'NY.GDP.MKTP.KD.ZG': 'GDP growth (annual %)',
 'SH.DYN.MORT': 'Mortality rate, under-5 (per 1,000 live births)',
 'SP.DYN.CBRT.IN': 'Birth rate, crude (per 1,000 people)',
 'SP.DYN.LE00.IN': 'Life expectancy at birth, total (years)',
 'SP.DYN.TFRT.IN': 'Fertility rate, total (births per woman)',
 'SP.POP.0014.TO': 'Population, ages 0-14, total',
 'SP.POP.1519.FE.5Y': 'Population ages 15-19, female (% of female population)',
 'SP.POP.1519.MA.5Y': 'Population ages 15-19, male (% of male population)',
 'SP.POP.2024.FE.5Y': 'Population ages 20-24, female (% of female population)',
 'SP.POP.2024.MA.5Y': 'Population ages 20-24, male (% of male population)',
 'SP.POP.2529.FE.5Y': 'Population ages 25-29, female (% of female population)',
 'SP.POP.2529.MA.5Y': 'Population ages 25-29, male (% of male population)',
 'SP.POP.3034.FE.5Y': 'Population ages 30-34, female (% of female population)',
 'SP.POP.3034.MA.5Y': 'Population ages 30-34, male (% of male population)',
 'SP.POP.3539.FE.5Y': 'Population ages 35-39, female (% of female population)',
 'SP.POP.3539.MA.5Y': 'Population ages 35-39, male (% of male population)',
 'SP.POP.4044.FE.5Y': 'Population ages 40-44, female (% of female population)',
 'SP.POP.4044.MA.5Y': 'Population ages 40-44, male (% of male population)',
 'SP.POP.4549.FE.5Y': 'Population ages 45-49, female (% of female population)',
 'SP.POP.4549.MA.5Y': 'Population ages 45-49, male (% of male population)',
 'SP.POP.5054.FE.5Y': 'Population ages 50-54, female (% of female population)',
 'SP.POP.5054.MA.5Y': 'Population ages 50-54, male (% of male population)',
 'SP.POP.5559.FE.5Y': 'Population ages 55-59, female (% of female population)',
 'SP.POP.5559.MA.5Y': 'Population ages 55-59, male (% of male population)',
 'SP.POP.6064.FE.5Y': 'Population ages 50-64, female (% of female population)',
 'SP.POP.6064.MA.5Y': 'Population ages 50-64, male (% of male population)',
 'SP.POP.65UP.TO.ZS': 'Population ages 65 and above (% of total)',
 'SP.POP.TOTL': 'Population, total',
 'SP.POP.TOTL.FE.IN': 'Population, female',
 'SP.POP.TOTL.MA.IN': 'Population, male',
 'SP.URB.GROW': 'Urban population growth (annual %)',
 'SP.URB.TOTL.IN.ZS': 'Urban population (% of total)'}

In [5]:
tabnames['Country Data']='Country Data'
tabnames['IncomeGroup']='IncomeGroup'
tabnames['Region']='Region'

In [6]:
countries=GetRegionIncomeDataWB()

In [7]:
countries

,Country Data,Region,IncomeGroup
country,,,
Afghanistan,AFG,South Asia,Low income
Albania,ALB,Europe & Central Asia,Upper middle income
Algeria,DZA,Middle East & North Africa,Upper middle income
American Samoa,ASM,East Asia & Pacific,Upper middle income
Andorra,AND,Europe & Central Asia,High income
Angola,AGO,Sub-Saharan Africa,Lower middle income
Antigua and Barbuda,ATG,Latin America & Caribbean,High income
Argentina,ARG,Latin America & Caribbean,Upper middle income
Armenia,ARM,Europe & Central Asia,Lower middle income
Aruba,ABW,Latin America & Caribbean,High income
Australia,AUS,East Asia & Pacific,High income
Austria,AUT,Europe & Central Asia,High income
Azerbaijan,AZE,Europe & Central Asia,Upper middle income
"Bahamas, The",BHS,Latin America & Caribbean,High income
Bahrain,BHR,Middle East & North Africa,High income
Bangladesh,BGD,South Asia,Lower middle income
Barbados,BRB,Latin America & Caribbean,High income
Belarus,BLR,Europe & Central Asia,Upper middle income
Belgium,BEL,Europe & Central Asia,High income
Belize,BLZ,Latin America & Caribbean,Upper middle income
Benin,BEN,Sub-Saharan Africa,Low income
Bermuda,BMU,North America,High income
Bhutan,BTN,South Asia,Lower middle income
Bolivia,BOL,Latin America & Caribbean,Lower middle income
Bosnia and Herzegovina,BIH,Europe & Central Asia,Upper middle income
Botswana,BWA,Sub-Saharan Africa,Upper middle income
Brazil,BRA,Latin America & Caribbean,Upper middle income
British Virgin Islands,VGB,Latin America & Caribbean,High income
Brunei Darussalam,BRN,East Asia & Pacific,High income
Bulgaria,BGR,Europe & Central Asia,Upper middle income
...,...,...,...
Sweden,SWE,Europe & Central Asia,High income
Switzerland,CHE,Europe & Central Asia,High income
Syrian Arab Republic,SYR,Middle East & North Africa,Lower middle income
Tajikistan,TJK,Europe & Central Asia,Lower middle income
Tanzania,TZA,Sub-Saharan Africa,Low income
Thailand,THA,East Asia & Pacific,Upper middle income
Timor-Leste,TLS,East Asia & Pacific,Lower middle income
Togo,TGO,Sub-Saharan Africa,Low income
Tonga,TON,East Asia & Pacific,Upper middle income
Trinidad and Tobago,TTO,Latin America & Caribbean,High income
Tunisia,TUN,Middle East & North Africa,Lower middle income
Turkey,TUR,Europe & Central Asia,Upper middle income
Turkmenistan,TKM,Europe & Central Asia,Upper middle income
Turks and Caicos Islands,TCA,Latin America & Caribbean,High income
Tuvalu,TUV,East Asia & Pacific,Upper middle income
Uganda,UGA,Sub-Saharan Africa,Low income
Ukraine,UKR,Europe & Central Asia,Lower middle income
United Arab Emirates,ARE,Middle East & North Africa,High income
United Kingdom,GBR,Europe & Central Asia,High income
United States,USA,North America,High income
Uruguay,URY,Latin America & Caribbean,High income
Uzbekistan,UZB,Europe & Central Asia,Lower middle income
Vanuatu,VUT,East Asia & Pacific,Lower middle income
"Venezuela, RB",VEN,Latin America & Caribbean,Upper middle income
Vietnam,VNM,East Asia & Pacific,Lower middle income
Virgin Islands (U.S.),VIR,Latin America & Caribbean,High income
West Bank and Gaza,PSE,Middle East & North Africa,Lower middle income
"Yemen, Rep.",YEM,Middle East & North Africa,Lower middle income
Zambia,ZMB,Sub-Saharan Africa,Lower middle income
Zimbabwe,ZWE,Sub-Saharan Africa,Low income

In [8]:
wbdata = GetDataWB(indicators, 2010, 2016)

In [ ]:
wbdata

In [ ]:
DataCompleteness(wbdata)

In [ ]:
wb_data_countries = countries.join(wbdata, how='inner')

In [ ]:
DataCompleteness(wb_data_countries)

In [ ]:
region_income_data=FillByRegionAndIncomeWB(wb_data_countries)

In [ ]:
DataCompleteness(region_income_data)

In [ ]:
income_data=FillByIncomeWB(region_income_data)

In [ ]:
DataCompleteness(income_data)

In [ ]:
region_data=FillByRegionWB(income_data)

In [ ]:
DataCompleteness(region_data)

In [ ]:
mean_data=FillWithMeanWB(region_data)

In [ ]:
DataCompleteness(mean_data)

In [ ]:
pop_data, tabnames = PopulationRangesWB(mean_data, tabnames)

In [ ]:
sorted_data = SortData(pop_data)

In [ ]:
sorted_data

In [ ]:
WriteToExcelWB(sorted_data, tabnames, filename='energydata.xlsx')